### ISSUE TITLE
Craft da Fornalha

### ISSUE THREAD

**Issue by HamiltonCosta** [CJMancini/The-Boreal-Expert#3]
![Screenshot_17](https://github.com/CJMancini/The-Boreal-Expert/assets/151444910/df438926-3f52-4174-b283-1e20803f61cb)
![Screenshot_18](https://github.com/CJMancini/The-Boreal-Expert/assets/151444910/b6a9fa66-479d-48bb-bc27-c95cd26fa760)

**Comment by CJMancini** [comment]
Resolvido próxima atualização (0.0.3.9)
